### PR TITLE
Fix external name configurations of `storage_container` and `storage_blob` resources

### LINKED ISSUE #129: azurerm_storage_container has wrong external-name in composition after creation
### What happened?

- Created a composition that has a storage container (`container.storage.azure.jet.crossplane.io`) resource
- Created a claim for the composition 
- Confirmed container was created in azure, external-name set to what was provided
- Once the container was created, the Crossplane observer failed, and the external name was set to 
```
<storageAccountName>.blob.core.windows.net/<containerName>
```

Details from the describe output:

```
Events:
  Type     Reason                         Age                    From                                                              Message
  ----     ------                         ----                   ----                                                              -------
  Normal   PendingExternalResource        4m28s (x4 over 5m17s)  managed/storage.azure.jet.crossplane.io/v1alpha2, kind=container  Waiting for external resource existence to be confirmed
  Normal   CreatedExternalResource        4m19s (x3 over 5m32s)  managed/storage.azure.jet.crossplane.io/v1alpha2, kind=container  Successfully requested creation of external resource
  Warning  CannotObserveExternalResource  30s (x35 over 4m)      managed/storage.azure.jet.crossplane.io/v1alpha2, kind=container  cannot run refresh: refresh failed: only lowercase alphanumeric characters and hyphens allowed in "name": "MY_ACCOUNT.blob.core.windows.net/test-lz-cnvnd": : File name: main.tf.json
```

### How can we reproduce it?

Create a composition with a storage container in it, and observe the behavior. 

### What environment did it happen in?
Crossplane version: v1.6.1
provider-jet-azure version: v0.6.0
kubernetes version: 1.21.7

### PR DESCRIPTION
**Pull request by sergenyalcin**
### Description of your changes

Fixes #129 

This PR resolves the configuration issues for the two resources.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

The external resources were provisioned by using the example manifests. Also the update and delete operations were tested.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: config/storage/config.go [hunk 1]
```diff
@@ -61,21 +59,11 @@ func Configure(p *config.Provider) {
...
-			}
-			idStr, ok := id.(string)
-			if !ok {
-				return "", errors.Errorf(common.ErrFmtUnexpectedType, "id")
-			}
-			idStr = strings.TrimSuffix(idStr, ".blob.core.windows.net/container/blob.vhd")
-			return strings.TrimPrefix(idStr, "https://"), nil
-		}
+		// https://storacc.blob.core.windows.net/container/blob.vhd
+		r.ExternalName.GetExternalNameFn = common.GetResourceNameFromIDURLFn(1)
```
Comment (ulucinar) [inline config/storage/config.go:63]: Nice!

**Review by ulucinar — APPROVED** [review]
Thank you @sergenyalcin.
